In [1]:
import numpy as np

In [2]:
score = np.random.randint(40,100,(10,5))

In [3]:
score

array([[40, 42, 46, 57, 87],
       [46, 91, 78, 62, 97],
       [84, 44, 48, 57, 46],
       [94, 81, 57, 65, 69],
       [50, 99, 70, 96, 79],
       [63, 92, 60, 49, 70],
       [75, 45, 68, 54, 42],
       [80, 68, 57, 71, 62],
       [99, 81, 71, 67, 76],
       [90, 49, 97, 86, 84]])

In [4]:
test_score = score[6:,0:5]

In [5]:
test_score

array([[75, 45, 68, 54, 42],
       [80, 68, 57, 71, 62],
       [99, 81, 71, 67, 76],
       [90, 49, 97, 86, 84]])

In [6]:
test_score[test_score>60]=1

In [7]:
test_score

array([[ 1, 45,  1, 54, 42],
       [ 1,  1, 57,  1,  1],
       [ 1,  1,  1,  1,  1],
       [ 1, 49,  1,  1,  1]])

In [8]:
# 判断前两名同学的成绩是否全及格
np.all(score[:2,:]>60)

False

In [9]:
# 判断前两名同学的成绩是否有大于90分的
np.any(score[:2,:]>90)

True

In [10]:
temp = score[:4, :4]
np.where(temp > 60, 1, 0)

array([[0, 0, 0, 0],
       [0, 1, 1, 1],
       [1, 0, 0, 0],
       [1, 1, 0, 1]])

# 统计运算

In [12]:
temp =score[:4,:]

In [13]:
temp

array([[40, 42, 46, 57, 87],
       [46, 91, 78, 62, 97],
       [84, 44, 48, 57, 46],
       [94, 81, 57, 65, 69]])

In [14]:
np.max(temp)

97

In [15]:
np.max(temp,axis=0)

array([94, 91, 78, 65, 97])

In [18]:
np.max(temp,axis=1)

array([87, 97, 84, 94])

In [16]:
np.mean(temp)

64.55

In [17]:
np.mean(temp,axis=0)

array([66.  , 64.5 , 57.25, 60.25, 74.75])

In [21]:
np.argmax(temp)

9

In [20]:
np.argmax(temp,axis=0)

array([3, 1, 1, 3, 1])

In [28]:
arr1 = np.array([[0],[1],[2],[3]])
arr1.shape
# (4, 1)

arr2 = np.array([[1,2,3]])
arr2.shape
# (3,)

arr1+arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [29]:
arr1 = np.array([[0],[1],[2],[3]])
arr1.shape
# (4, 1)

arr2 = np.array([1,2,3])
arr2.shape
# (3,)

arr1+arr2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])